@ECHO KILL NICE MINERS
taskkill /f /im prospector.exe
taskkill /f /im Optiminer.exe
taskkill /f /im ZecMiner64.exe
taskkill /f /im EthDcrMiner64.exe
taskkill /f /im NsGpuCNMiner.exe
taskkill /f /im xmr-stak-cpu.exe
taskkill /f /im sgminer.exe
taskkill /f /im nheqminer.exe
taskkill /f /im excavator.exe
taskkill /f /im ethminer.exe
taskkill /f /im ccminer.exe
taskkill /f /im miner.exe
